"""Initial MIgration

Revision ID: dd3e1caca2bf
Revises: 
Create Date: 2024-02-22 09:58:38.209547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd3e1caca2bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('BudgetID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Amount', sa.Float(), nullable=False),
    sa.Column('Category', sa.String(length=50), nullable=False),
    sa.Column('StartDate', sa.Date(), nullable=False),
    sa.Column('EndDate', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['UserID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('BudgetID')
    )
    op.create_table('transactions',
    sa.Column('TransactionID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Amount', sa.Float(), nullable=False),
    sa.Column('Category', sa.String(length=50), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('Date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('TransactionID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('budgets')
    # ### end Alembic commands ###
